### PR TITLE
implement optional file size optimization

### PR DESCRIPTION
**Pull request by rudigiesler**

### CODE REVIEW

**Comment by rudigiesler** [comment]
https://github.com/rudigiesler/mathml-to-image-service/blob/master/mathml_to_image_service/svg_to_image.py#L47

**Comment by zoidyzoidzoid** [comment]
I merged #13, so you'll have to merge master back into it.

**Comment by zoidyzoidzoid** [comment]
What do you think about having a default quality?

**Comment by rudigiesler** [comment]
I think that the approach we were taking is no default values for any of the parameters, and that it should give an error if anything is missing, for people who don't read the docs?

**Comment by zoidyzoidzoid** [comment]
Yeah, I remember @jonathanendersby saying that.

I guess once we have to worry about backwards compatibility then when we add more things we can worry about some things having defaults.

**Comment by rudigiesler** [comment]
It's not being used anywhere yet, and we haven't done a version release, so I think it's okay to add these things until we do a release.

**Comment by zoidyzoidzoid** [comment]
Yeah, that's what I was trying to get at. Agreed. :+1:

**Pull request merged**
