### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### rudigiesler/mathml-to-image-service now has a Chat Room on Gitter

@zoidbergwill has just created a chat room. You can visit it here: [https://gitter.im/rudigiesler/mathml-to-image-service](https://gitter.im/rudigiesler/mathml-to-image-service?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/rudigiesler/mathml-to-image-service?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by zoidyzoidzoid** [comment]
Grrr, I didn't know it did this.

**Comment by rudigiesler** [comment]
I don't know if we want this badge on the README? Can we close this pull request?

**Comment by zoidyzoidzoid** [comment]
Yeah. :fire:

**Comment by gitter-badger** [comment]
Hi @zoidbergwill, apologies for the pull-request. It's a new feature we've been trialling over the past week or so and the feedback has been very positive. If you would like to opt-out, click the link in the email and we won't send you any more pull-requests. 

If you would like to discuss more, please feel free to drop into https://gitter.im/gitterHQ/gitter to chat about it.

**Pull request closed without merging**
